include core/arch/arm/cpu/cortex-armv8-0.mk

$(call force,CFG_TEE_CORE_NB_CORE,4)

CFG_TZDRAM_START ?= 0x8a680000
CFG_TZDRAM_SIZE ?= 0x280000
CFG_TEE_RAM_VA_SIZE ?= 0x280000

$(call force,CFG_ARM64_core,y)
$(call force,CFG_SECURE_TIME_SOURCE_CNTPCT,y)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)

CFG_NUM_THREADS ?= CFG_TEE_CORE_NB_CORE
CFG_CRYPTO_WITH_CE ?= n

CFG_TEE_CORE_EMBED_INTERNAL_TESTS ?= n
CFG_WITH_STACK_CANARIES ?= n
CFG_WITH_STATS ?= n
CFG_CORE_RESERVED_SHM ?= n

CFG_TA_ASLR ?= n
CFG_CORE_ASLR ?= n

$(call force,CFG_CRYPTO_SHA256_ARM32_CE,n)
$(call force,CFG_CRYPTO_SHA256_ARM64_CE,n)
$(call force,CFG_CRYPTO_SHA1_ARM32_CE,n)
$(call force,CFG_CRYPTO_SHA1_ARM64_CE,n)
$(call force,CFG_CRYPTO_AES_ARM64_CE,n)
