/* SPDX-License-Identifier: ISC */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#include <mm/generic_ram_layout.h>

#define STACK_ALIGNMENT		64

#define GIC_BASE			CFG_GIC_BASE
#define GIC_SIZE			CFG_GIC_SIZE
#define GICD_OFFSET			CFG_GICD_OFFSET
#define GICD_BASE			(GIC_BASE + GICD_OFFSET)
#if defined(CFG_ARM_GICV3)
#define GICR_OFFSET			CFG_GICR_OFFSET
#define GICR_BASE			(GIC_BASE + GICR_OFFSET)
#else /* ! CFG_ARM_GICV3 */
#define GICC_OFFSET			CFG_GICC_OFFSET
#define GICC_BASE			(GIC_BASE + GICC_OFFSET)
/* Override PIDR2 Register offset in generic GIC driver */
#define GICD_PIDR2			0xFD8
#define QCOM_EL3_INTR_DELEGATION_SVC_ID	0x02001D03
#endif

#if defined(CFG_QCOM_GENI_UART)
#define QUP_UART_BASE			CFG_QCOM_QUP_UART_BASE
#define QUP_UART_REG_SIZE		CFG_QCOM_QUP_UART_SIZE
#endif

#if defined(CFG_QCOM_DIAG_LOG)
#define DIAG_BASE			CFG_QCOM_DIAG_BASE
#define DIAG_SIZE			CFG_QCOM_DIAG_SIZE
#define DIAG_LOG_START_INFO		CFG_QCOM_DIAG_LOG_START_INFO
#define DIAG_LOG_SIZE_INFO		CFG_QCOM_DIAG_LOG_SIZE_INFO
#define TCSR_BOOT_MISC_DETECT		CFG_QCOM_TCSR_BOOT_MISC_DETECT
#endif

#if defined(CFG_QCOM_TMEL_COM)
#define TME_QMP_INBOUND_MBOX_ADDR	CFG_TME_QMP_INBOUND_MBOX_ADDR
#define TME_QMP_OUTBOUND_MBOX_ADDR	CFG_TME_QMP_OUTBOUND_MBOX_ADDR
/* Incoming Interrupt: TME -> APSS */
#define TME_QMP_IRQ_IN			CFG_TME_QMP_IRQ_IN_ID
/* Outgoing Interrupt: APSS -> TME (APCS_*_TZ_IPC_INTERRUPT)  */
#define TME_QMP_IRQ_OUT_REG_ADDR	CFG_TME_QMP_IRQ_OUT_REG_ADDR
#define TME_QMP_IRQ_OUT_BIT_MASK	CFG_TME_QMP_IRQ_OUT_BIT_MASK
/* FEATURE_CONFIG2 fuse register - indicates if TMEL is bypassed on this part */
#define FEATURE_CONFIG2_ADDR			CFG_QCOM_FEATURE_CONFIG2_ADDR
#define FEATURE_CONFIG2_TMEL_BYPASS_DISABLE_BMSK	0x1
#endif

/* DDR memory configuration */
#ifdef CFG_DRAM0_BASE
#define DRAM0_BASE			CFG_DRAM0_BASE
#define DRAM0_SIZE			CFG_DRAM0_SIZE
#endif

#ifdef CFG_DRAM1_BASE
#define DRAM1_BASE			CFG_DRAM1_BASE
#define DRAM1_SIZE			CFG_DRAM1_SIZE
#endif

#endif /* PLATFORM_CONFIG_H */
