/* SPDX-License-Identifier: ISC */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef PLATFORM_CONFIG_H
#define PLATFORM_CONFIG_H

#include <mm/generic_ram_layout.h>

#define STACK_ALIGNMENT		64
#define IMEM_BASE                       CFG_IMEM_BASE
#define IMEM_MPU_BASE			CFG_IMEM_MPU_BASE
#define TCSR_BASE                       CFG_TCSR_BASE
#define GIC_BASE			CFG_GIC_BASE
#define GIC_SIZE			CFG_GIC_SIZE
#define GICD_OFFSET			CFG_GICD_OFFSET
#define GICD_BASE			(GIC_BASE + GICD_OFFSET)
#if defined(CFG_ARM_GICV3)
#define GICR_OFFSET			CFG_GICR_OFFSET
#define GICR_BASE			(GIC_BASE + GICR_OFFSET)
#else /* ! CFG_ARM_GICV3 */
#define GICC_OFFSET			CFG_GICC_OFFSET
#define GICC_BASE			(GIC_BASE + GICC_OFFSET)
/* Override PIDR2 Register offset in generic GIC driver */
#define GICD_PIDR2			0xFD8
#define QCOM_EL3_INTR_DELEGATION_SVC_ID	0x02001D03
#endif

#if defined(CFG_DRIVERS_QCOM_CLK)
#define GCC_BASE			0x01800000
#define GCC_SIZE			0x40000
#endif

#if defined(CFG_QCOM_GENI_UART)
#define GENI_UART_REG_BASE		CFG_GENI_UART_BASE
#endif

#if defined(CFG_QCOM_DIAG_LOG)
#define DIAG_BASE			CFG_QCOM_DIAG_BASE
#define DIAG_SIZE			CFG_QCOM_DIAG_SIZE
#define DIAG_LOG_START_INFO		CFG_QCOM_DIAG_LOG_START_INFO
#define DIAG_LOG_SIZE_INFO		CFG_QCOM_DIAG_LOG_SIZE_INFO
#define TCSR_BOOT_MISC_DETECT		CFG_QCOM_TCSR_BOOT_MISC_DETECT
#define IMEM_XPU_LOG_RG			CFG_IMEM_XPU_LOG_RG
#define IMEM_XPU_LOG_READ_QAD		CFG_IMEM_XPU_LOG_READ_QAD
#endif

#if defined(CFG_QCOM_TMEL_COM)
#define TME_QMP_INBOUND_MBOX_ADDR	CFG_TME_QMP_INBOUND_MBOX_ADDR
#define TME_QMP_OUTBOUND_MBOX_ADDR	CFG_TME_QMP_OUTBOUND_MBOX_ADDR
/* Incoming Interrupt: TME -> APSS */
#define TME_QMP_IRQ_IN			CFG_TME_QMP_IRQ_IN_ID
/* Outgoing Interrupt: APSS -> TME (APCS_*_TZ_IPC_INTERRUPT)  */
#define TME_QMP_IRQ_OUT_REG_ADDR	CFG_TME_QMP_IRQ_OUT_REG_ADDR
#define TME_QMP_IRQ_OUT_BIT_MASK	CFG_TME_QMP_IRQ_OUT_BIT_MASK
/* FEATURE_CONFIG2 fuse register - indicates if TMEL is bypassed on this part */
#define FEATURE_CONFIG2_ADDR			CFG_QCOM_FEATURE_CONFIG2_ADDR
#define FEATURE_CONFIG2_TMEL_BYPASS_DISABLE_BMSK	0x1

#if defined(CFG_QCOM_TMEL_KM)
/* TCSR Hardware Key Register Configuration */
#define TCSR_FUSE_PRI_HW_KEY_BASE_START	CFG_TCSR_FUSE_PRI_HW_KEY_BASE_START
#define TCSR_FUSE_PRI_HW_KEY_REG_COUNT	CFG_TCSR_FUSE_PRI_HW_KEY_REG_COUNT
#define TCSR_FUSE_SEC_HW_KEY_BASE_START	CFG_TCSR_FUSE_SEC_HW_KEY_BASE_START
#define TCSR_FUSE_SEC_HW_KEY_REG_COUNT	CFG_TCSR_FUSE_SEC_HW_KEY_REG_COUNT
#endif
#endif

#if defined(CFG_QCOM_SEC_WDOG)
#define APSS_WDT_TMR2_BASE		CFG_APSS_WDT_BASE
#define WDOG_RESET_REG_OFFSET		CFG_WDOG_RESET_REG_OFFSET
#define SEC_WDOG_BARK_INT_ID		CFG_SEC_WDOG_BARK_INT_ID
#endif

#if defined(CFG_QCOM_HUK)
#define QCOM_SERIAL_NUM_FUSE_ADDR		CFG_QCOM_SERIAL_NUM_FUSE_ADDR
#endif

#if defined(CFG_EMMC_ICE_FS_ENC_PTA)
#define SDCC_ICE_LUT_KEYS			CFG_SDCC_ICE_LUT_KEYS
#define SDCC_ICE_LUT_KEYS_SIZE			CFG_SDCC_ICE_LUT_KEYS_SIZE
#define TCSR_KEYSLOT_ADDR			CFG_TCSR_KEYSLOT_ADDR
#endif

#if defined(CFG_QCOM_QRNG)
#define QRNG_BASE_ADDR				CFG_QRNG_BASE_ADDR
#define QRNG_EE5_BASE_ADDR			CFG_QRNG_EE5_BASE_ADDR
#endif

/* DDR memory configuration */
#ifdef CFG_DRAM0_BASE
#define DRAM0_BASE			CFG_DRAM0_BASE
#define DRAM0_SIZE			CFG_DRAM0_SIZE
#endif

#ifdef CFG_DRAM1_BASE
#define DRAM1_BASE			CFG_DRAM1_BASE
#define DRAM1_SIZE			CFG_DRAM1_SIZE
#endif

/* PAS (Peripheral Authentication Service) IDs for CDSP */
#if defined(PLATFORM_FLAVOR_ipq96xx) || defined(PLATFORM_FLAVOR_ipq96xx_lm)
#define PAS_ID_CDSP			18
#define PAS_ID_CDSP_DTB			37
#define SW_ID_CDSP          23
#define SW_ID_CDSP_DTB      82
#endif

#endif /* PLATFORM_CONFIG_H */
