# IPQ Low Memory (LM) Profile Configuration

# Memory size configuration for LM profile
CFG_TZDRAM_SIZE ?= 0x80000
CFG_TEE_RAM_VA_SIZE ?= 0x80000

# Reduce heap size to 32KB for minimal feature set
CFG_CORE_HEAP_SIZE ?= 0x8000

# GENI UART support
CFG_QCOM_GENI_UART ?= y

# TME IPC support
CFG_QCOM_TMEL_COM ?= y

# Disable unnecessary crypto algorithms
CFG_CRYPTO_DES ?= n
CFG_CRYPTO_SM4 ?= n
CFG_CRYPTO_CBC ?= n
CFG_CRYPTO_GCM ?= n
CFG_CRYPTO_CTR ?= n
CFG_CRYPTO_CTS ?= n
CFG_CRYPTO_XTS ?= n
CFG_CRYPTO_HMAC ?= n
CFG_CRYPTO_CMAC ?= n
CFG_CRYPTO_CBC_MAC ?= n
CFG_CRYPTO_MD5 ?= n
CFG_CRYPTO_SHA1 ?= n
CFG_CRYPTO_SHA224 ?= n
CFG_CRYPTO_SHA384 ?= n
CFG_CRYPTO_SHA512 ?= n
CFG_CRYPTO_SHA512_256 ?= n
CFG_CRYPTO_SM3 ?= n
CFG_CRYPTO_SHA3_224 ?= n
CFG_CRYPTO_SHA3_256 ?= n
CFG_CRYPTO_SHA3_384 ?= n
CFG_CRYPTO_SHA3_512 ?= n
CFG_CRYPTO_SHAKE128 ?= n
CFG_CRYPTO_SHAKE256 ?= n
CFG_CRYPTO_CONCAT_KDF ?= n
CFG_CRYPTO_HKDF ?= n
CFG_CRYPTO_PBKDF2 ?= n
CFG_CRYPTO_DSA ?= n
CFG_CRYPTO_RSA ?= n
CFG_CRYPTO_DH ?= n
CFG_CRYPTO_ECC ?= n
CFG_CRYPTO_SM2_PKE ?= n
CFG_CRYPTO_SM2_DSA ?= n
CFG_CRYPTO_SM2_KEP ?= n
CFG_CRYPTO_ED25519 ?= n
CFG_CRYPTO_X25519 ?= n
CFG_CRYPTO_CCM ?= n

# Disable TAs
CFG_WITH_USER_TA ?= n
CFG_BUILD_IN_TREE_TA ?= n
CFG_PKCS11_TA ?= n
CFG_IN_TREE_EARLY_TAS :=

# Disable file systems and secure storage
CFG_REE_FS ?= n
CFG_REE_FS_TA ?= n

# Disable security hardening
CFG_TA_FLOAT_SUPPORT ?= n

# Disable other features
CFG_FAULT_MITIGATION ?= n
CFG_COMPAT_GP10_DES ?= n
CFG_CORE_HUK_SUBKEY_COMPAT ?= n
CFG_PREALLOC_RPC_CACHE ?= n
