/* SPDX-License-Identifier: ISC */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __DRIVERS_QCOM_QFPROM_IPQ96XX_H
#define __DRIVERS_QCOM_QFPROM_IPQ96XX_H

#include <drivers/qcom/qfprom.h>
#include <util.h>

/*
 * TME OEM MRC State Vector Definitions
 */
#define TMEL_OEMMRCSTATEVECTOR_ADDR			0x000A0098

#define TME_OEM_MRC_ACTIVATION_VECTOR_BITS		0x8
#define TME_OEM_MRC_ACTIVATION_VECTOR_MASK		0xFF
#define TME_OEM_MRC_REVOCATION_VECTOR_MASK		0xFF

/* QFPROM RAW region addresses for FEC-enabled ranges */
#define HWIO_QFPROM_RAW_TME_OEM_MRC_HASH_ROW0_LSB_ADDR	0x000A0100
#define HWIO_QFPROM_RAW_TME_OEM_MRC_HASH_ROW9_LSB_ADDR	0x000A0148
#define HWIO_QFPROM_RAW_TME_OEM_PRDT_SEED_ROW0_LSB_ADDR	0x000A02C8
#define HWIO_QFPROM_RAW_TME_OEM_PRDT_SEED_ROW4_LSB_ADDR	0x000A02E8
#define HWIO_QFPROM_RAW_OEM_CONFIG2_ROW0_LSB_ADDR	0x000A06C0
#define HWIO_QFPROM_RAW_OEM_SPARE_REGION_31_LSB_ADDR	0x000A06C8
#define HWIO_QFPROM_RAW_RSVD_OEM_SECURE_BOOT_LSB_ADDR	0x000A0328
#define HWIO_QFPROM_RAW_RSVD_PK_HASH_ROW6_LSB_ADDR	0x000A0360

/*
 * FEC-enabled fuse ranges
 */
static const struct fec_fuse_range fec_enabled_ranges[] = {
	/* TME OEM MRC Hash region */
	{ HWIO_QFPROM_RAW_TME_OEM_MRC_HASH_ROW0_LSB_ADDR,
	  HWIO_QFPROM_RAW_TME_OEM_MRC_HASH_ROW9_LSB_ADDR },
	/* TME OEM PRDT Seed region */
	{ HWIO_QFPROM_RAW_TME_OEM_PRDT_SEED_ROW0_LSB_ADDR,
	  HWIO_QFPROM_RAW_TME_OEM_PRDT_SEED_ROW4_LSB_ADDR },
	/* OEM Config2 region */
	{ HWIO_QFPROM_RAW_OEM_CONFIG2_ROW0_LSB_ADDR,
	  HWIO_QFPROM_RAW_OEM_SPARE_REGION_31_LSB_ADDR },
	/* OEM Secure boot region */
	{ HWIO_QFPROM_RAW_RSVD_OEM_SECURE_BOOT_LSB_ADDR,
	  HWIO_QFPROM_RAW_RSVD_PK_HASH_ROW6_LSB_ADDR },
};

#define FEC_NUM_RANGES	ARRAY_SIZE(fec_enabled_ranges)

#endif /* __DRIVERS_QCOM_QFPROM_IPQ96XX_H */
