// SPDX-License-Identifier: ISC
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __ICE_CONFIG_H
#define __ICE_CONFIG_H

#include <stdint.h>
#include <platform_config.h>

/* ICE Register Definitions */
#define SDC1_SDCC_ICE_CRYPTOCFG_r_n_ADDR(r, n) \
	(SDCC_ICE_LUT_KEYS + 0x0 + (0x80 * (r)) + (0x4 * (n)))
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_ADDR(r) \
	(SDCC_ICE_LUT_KEYS + 0x40 + (0x80 * (r)))
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_CFGE_BMSK		0x80000000
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_CFGE_SHFT		31
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_CAPIDX_BMSK	0xff00
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_CAPIDX_SHFT	8
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_DUSIZE_BMSK	0xff
#define SDC1_SDCC_ICE_CRYPTOCFG_r_16_DUSIZE_SHFT	0

#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_ADDR(r) \
	(SDCC_ICE_LUT_KEYS + 0x44 + (0x80 * (r)))
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_KEY_SELECTION_BMSK	0x300000
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_KEY_SELECTION_SHFT	20
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_DECR_BYPASS_BMSK	0x20000
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_DECR_BYPASS_SHFT	17
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_ENCR_BYPASS_BMSK	0x10000
#define SDC1_SDCC_ICE_CRYPTOCFG_r_17_ENCR_BYPASS_SHFT	16

#define SDC1_SDCC_ICE_SEC_CONTROL_ADDR \
	(SDCC_ICE_LUT_KEYS + 0x110c)
#define SDC1_SDCC_ICE_SEC_CONTROL_CRYPTOCFG_VS_BITS_EN_BMSK 0x20
#define SDC1_SDCC_ICE_SEC_CONTROL_CRYPTOCFG_VS_BITS_EN_SHFT 5

#define SDC1_SDCC_ICE_HWKEY0_CAPIDX_ADDR \
	(SDCC_ICE_LUT_KEYS + 0x1200)
#define SDC1_SDCC_ICE_HWKEY1_CAPIDX_ADDR \
	(SDCC_ICE_LUT_KEYS + 0x1204)

#define TCSR_KEYSLOT_ALGO_ALLOWED_BMSK		0xFC000
#define TCSR_KEYSLOT_ALGO_ALLOWED_SHFT		14

#define ICE_MAX_KEY_IDX				32
#define ICE_CRYPTOCFG_DATA_REGS			16

#define EMMC_CE					20
#define UFS_CE					10
#define UFS_CARD_CE				30

#define ICE_CRYPTO_KEY_SIZE_128			0x0
#define ICE_CRYPTO_KEY_SIZE_256			0x2

#define ICE_CRYPTO_ALGO_MODE_AES_ECB		0x0
#define ICE_CRYPTO_ALGO_MODE_AES_XTS		0x3
#define ICE_CRYPTO_ALGO_MODE_BITLOCKER		0x7

#define ICE_CRYPTO_USE_KEY0_HW_KEY		0x0
#define ICE_CRYPTO_USE_KEY1_HW_KEY		0x1
#define ICE_CRYPTO_USE_LUT_SW_KEY		0x3

#define BYPASS_DISABLE				0x0
#define BYPASS_ENABLE				0x1

#define ICE_CRYPTO_CRBK_TYPE			0x0
#define ICE_CRYPTO_OEMPRODSEED_TYPE		0x1

#define TME_KDF_SW_CONTEXT_BYTES_MAX		128
#define TME_KDF_SALT_LABEL_BYTES_MAX		64
#define TMEL_ICE_ENDPOINT_SALT_KEY_SLOT_2	0x0
#define TMEL_ICE_ENDPOINT_DATA_KEY_SLOT_3	0x1

#define TME_KD_ICE				0x00000080

typedef enum {
	ICE_CIPHER_MODE_XTS_128 = 0x0,
	ICE_CIPHER_MODE_CBC_128 = 0x1,
	ICE_CIPHER_MODE_ECB_128 = 0x2,
	ICE_CIPHER_MODE_XTS_256 = 0x3,
	ICE_CIPHER_MODE_CBC_256 = 0x4,
	ICE_CIPHER_MODE_ECB_256 = 0x5
} ice_capability_index_type;

typedef enum {
	ICE_DATA_UNIT_SIZE_512   = 0x1,
	ICE_DATA_UNIT_SIZE_1024  = 0x2,
	ICE_DATA_UNIT_SIZE_2048  = 0x4,
	ICE_DATA_UNIT_SIZE_4096  = 0x8,
	ICE_DATA_UNIT_SIZE_8192  = 0x10,
	ICE_DATA_UNIT_SIZE_16384 = 0x20,
	ICE_DATA_UNIT_SIZE_32768 = 0x40,
	ICE_DATA_UNIT_SIZE_65536 = 0x80
} ice_data_unit_type;

typedef struct {
	uint32_t index;
	uint8_t key_len;
	uint8_t alg_mode;
	uint8_t key_mode;
} __packed ice_set_key_config_context_req;

typedef struct {
	uint32_t seed_type;
	uint8_t key_size;
	uint8_t algo_mode;
} __packed ice_context_config;

typedef enum {
	CIPHER_ALGO_AES_128 = 0,
	CIPHER_ALGO_AES_256 = 1
} cipher_algo_et;

#endif /* __ICE_CONFIG_H */
